# 📊 Data Science — Etapa 3: Preparação dos Dados
## 🚗 Dataset Uber — Pandas × Polars

### Objetivos

Nesta aula vamos preparar um dataset real de corridas de Uber utilizando **Pandas** e **Polars**.

Ao final, você deverá ser capaz de:

- carregar e inspecionar um dataset;
- identificar tipos de dados incorretos;
- investigar valores ausentes;
- identificar duplicidades;
- corrigir problemas de formatação;
- analisar inconsistências considerando o contexto do negócio;
- criar novas variáveis com *Feature Engineering*;
- realizar agregações;
- comparar Pandas e Polars.

> **Regra de ouro:** antes de corrigir um dado, procure entender por que ele está daquela maneira.

## 🗑️ 1. Garbage In, Garbage Out — GIGO

> **Garbage In, Garbage Out:** se dados ruins forem utilizados como entrada, os resultados produzidos pelo sistema também poderão ser ruins.

A preparação dos dados é uma das etapas mais importantes de um projeto de Data Science.

Antes de aplicar algoritmos como:

- Regressão;
- Random Forest;
- XGBoost;
- Redes Neurais;

precisamos entender a qualidade do dataset.

### Dataset utilizado

```text
uber.csv
```

O arquivo contém informações sobre corridas, clientes, motoristas, localização, valores, distâncias, avaliações e cancelamentos.

## 📦 2. Importando as bibliotecas

In [2]:
import pandas as pd
import polars as pl

pd.set_option("display.max_columns", None)

## 📥 3. Carregando o dataset

In [3]:
# Pandas
df_pd = pd.read_csv("uber.csv")

# Polars
df_pl = pl.read_csv("uber.csv")

print("Pandas:", df_pd.shape)
print("Polars:", df_pl.shape)

Pandas: (150000, 21)
Polars: (150000, 21)

## 🔎 4. Conhecendo o dataset

Antes de modificar qualquer coisa, devemos investigar os dados.

In [5]:
# Primeiras linhas — Pandas
df_pd.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,NaN,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,NaN,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,NaN,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,NaN,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [6]:
# Primeiras linhas — Polars
df_pl.head()

shape: (5, 21)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Date      ┆ Time     ┆ Booking   ┆ Booking   ┆ … ┆ Ride      ┆ Driver    ┆ Customer  ┆ Payment   │
│ ---       ┆ ---      ┆ ID        ┆ Status    ┆   ┆ Distance  ┆ Ratings   ┆ Rating    ┆ Method    │
│ str       ┆ str      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2024-03-2 ┆ 12:29:38 ┆ "CNR58843 ┆ No Driver ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 3         ┆          ┆ 00"       ┆ Found     ┆   ┆           ┆           ┆           ┆           │
│ 2024-11-2 ┆ 18:01:39 ┆ "CNR13268 ┆ Incomplet ┆ … ┆ 5.73      ┆ null      ┆ null      ┆ UPI       │
│ 9         ┆          ┆ 09"       ┆ e         ┆   ┆           ┆           ┆           ┆           │
│ 2024-08-2 ┆ 08:56:10 ┆ "CNR84945 ┆ Completed ┆ … ┆ 13.58     ┆ 4.9       ┆ 4.9       ┆ Debit     │
│ 3         ┆          ┆ 06"       ┆           ┆   ┆           ┆           ┆           ┆ Card      │
│ 2024-10-2 ┆ 17:17:25 ┆ "CNR89068 ┆ Completed ┆ … ┆ 34.02     ┆ 4.6       ┆ 5.0       ┆ UPI       │
│ 1         ┆          ┆ 25"       ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2024-09-1 ┆ 22:08:00 ┆ "CNR19501 ┆ Completed ┆ … ┆ 48.21     ┆ 4.1       ┆ 4.3       ┆ UPI       │
│ 6         ┆          ┆ 62"       ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
# Colunas
print("Pandas:")
print(df_pd.columns)

print("\nPolars:")
print(df_pl.columns)

Pandas:
Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Cancelled Rides by Customer',
       'Reason for cancelling by Customer', 'Cancelled Rides by Driver',
       'Driver Cancellation Reason', 'Incomplete Rides',
       'Incomplete Rides Reason', 'Booking Value', 'Ride Distance',
       'Driver Ratings', 'Customer Rating', 'Payment Method'],
      dtype='object')

Polars:
['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID', 'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT', 'Avg CTAT', 'Cancelled Rides by Customer', 'Reason for cancelling by Customer', 'Cancelled Rides by Driver', 'Driver Cancellation Reason', 'Incomplete Rides', 'Incomplete Rides Reason', 'Booking Value', 'Ride Distance', 'Driver Ratings', 'Customer Rating', 'Payment Method']

## 📏 5. Dimensões do dataset

In [6]:
# Pandas
print("Pandas:", df_pd.shape)

# Polars
print("Polars:", df_pl.shape)

Pandas: (150000, 21)
Polars: (150000, 21)

## 🧬 6. Tipos de dados

Uma pergunta importante é:

> O tipo armazenado corresponde ao significado da variável?

Por exemplo, `Date` representa uma data e `Time` representa um horário. Se forem carregados como texto, precisaremos corrigi-los.

In [ ]:
# Pandas
df_pd.info() #info() exibe informações resumidas sobre o DataFrame, incluindo o número de entradas, o número de colunas, os nomes das colunas, os tipos de dados de cada coluna, a contagem de valores não nulos em cada coluna e a quantidade de memória usada pelo DataFrame.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Avg VTAT                           139500 non-null  float64
 9   Avg CTAT                           102000 non-null  float64
 10  Cancelled Rides by Customer        10500 non-null   float64
 11  Reason for cancelling by Customer  10500 non-null   object
 12  Cancelled Rides by Driver          27000 non-null   float64
 13  Driver Cancellation Reason         27000 non-null   object
 14  Incomplete Rides                   9000 non-null    float64
 15  Incomplete Rides Reason            9000 non-null    object
 16  Booking Value                      102000 non-null  float64
 17  Ride Distance                      102000 non-null  float64
 18  Driver Ratings                     93000 non-null   float64
 19  Customer Rating                    93000 non-null   float64
 20  Payment Method                     102000 non-null  object
dtypes: float64(9), object(12)
memory usage: 24.0+ MB

In [ ]:
# Tipos no Polars
df_pl.schema #schema retorna um dicionário com os nomes das colunas como chaves e os tipos de dados correspondentes como valores, permitindo uma visão geral da estrutura do DataFrame.

Schema([('Date', String),
        ('Time', String),
        ('Booking ID', String),
        ('Booking Status', String),
        ('Customer ID', String),
        ('Vehicle Type', String),
        ('Pickup Location', String),
        ('Drop Location', String),
        ('Avg VTAT', String),
        ('Avg CTAT', String),
        ('Cancelled Rides by Customer', String),
        ('Reason for cancelling by Customer', String),
        ('Cancelled Rides by Driver', String),
        ('Driver Cancellation Reason', String),
        ('Incomplete Rides', String),
        ('Incomplete Rides Reason', String),
        ('Booking Value', String),
        ('Ride Distance', String),
        ('Driver Ratings', String),
        ('Customer Rating', String),
        ('Payment Method', String)])

## 🧹 7. Problema de formatação — IDs

Vamos verificar os identificadores.

Observe se aparecem valores como:

```text
"CNR5884300"
```

As aspas podem fazer parte do conteúdo e podem ser removidas.

In [9]:
df_pd[["Booking ID", "Customer ID"]].head(10)

     Booking ID   Customer ID
0  "CNR5884300"  "CID1982111"
1  "CNR1326809"  "CID4604802"
2  "CNR8494506"  "CID9202816"
3  "CNR8906825"  "CID2610914"
4  "CNR1950162"  "CID9933542"
5  "CNR4096693"  "CID4670564"
6  "CNR2002539"  "CID6800553"
7  "CNR6568000"  "CID8610436"
8  "CNR4510807"  "CID7873618"
9  "CNR7721892"  "CID5214275"

In [10]:
# Pandas
df_pd["Booking ID"] = df_pd["Booking ID"].str.replace('"', '', regex=False)
df_pd["Customer ID"] = df_pd["Customer ID"].str.replace('"', '', regex=False)

df_pd[["Booking ID", "Customer ID"]].head()

   Booking ID Customer ID
0  CNR5884300  CID1982111
1  CNR1326809  CID4604802
2  CNR8494506  CID9202816
3  CNR8906825  CID2610914
4  CNR1950162  CID9933542

In [55]:
# Polars
df_pl = df_pl.with_columns(
    pl.col("Booking ID").str.strip_chars('"'),
    pl.col("Customer ID").str.strip_chars('"')
)

df_pl.select(["Booking ID", "Customer ID"]).head()

shape: (5, 2)
┌────────────┬─────────────┐
│ Booking ID ┆ Customer ID │
│ ---        ┆ ---         │
│ str        ┆ str         │
╞════════════╪═════════════╡
│ CNR5884300 ┆ CID1982111  │
│ CNR1326809 ┆ CID4604802  │
│ CNR8494506 ┆ CID9202816  │
│ CNR8906825 ┆ CID2610914  │
│ CNR1950162 ┆ CID9933542  │
└────────────┴─────────────┘

In [56]:
# 1. Imprimir diretamente a primeira string (não renderiza como HTML do DataFrame)
print("Valor real na memória:", df_pl["Booking ID"][0])
# Saída: Valor real na memória: CNR5884300

Valor real na memória: CNR5884300

In [ ]:
###Pandas: Mostra textos sem aspas na tabela renderizada.

###Polars: Coloca aspas em dados str na tabela do notebook para explicitar que aquele valor é uma string e não um número ou identificador sem tipo.

## 📅 8. Convertendo `Date`

A coluna `Date` deve ser tratada como data.

In [ ]:
# Pandas
df_pd["Date"] = pd.to_datetime(df_pd["Date"], errors="coerce") #coerce para lidar com valores inválidos, 
                                                                #caso seja necessário por exemplo, se houver valores nulos ou em formatos diferentes do esperado ele não vai gerar erro, mas sim retornar nulo para esses casos

df_pd[["Date"]].head()

        Date
0 2024-03-23
1 2024-11-29
2 2024-08-23
3 2024-10-21
4 2024-09-16

In [ ]:
# Polars
df_pl = df_pl.with_columns(   #with_columns para criar novas colunas ou modificar colunas existentes, 
                                #ele percorre todas as colunas especificadas e aplica as transformações desejadas, retornando um novo DataFrame com as alterações
    pl.col("Date").str.to_date(strict=False)#strict=False para lidar com valores inválidos, 
                                                                #caso seja necessário por exemplo, se houver valores nulos ou em formatos diferentes do esperado ele não vai gerar erro, mas sim retornar nulo para esses casos

)

df_pl.select("Date").head()

shape: (5, 1)
┌────────────┐
│ Date       │
│ ---        │
│ date       │
╞════════════╡
│ 2024-03-23 │
│ 2024-11-29 │
│ 2024-08-23 │
│ 2024-10-21 │
│ 2024-09-16 │
└────────────┘

## ⏰ 9. Trabalhando com `Time`

O horário pode ser convertido para um tipo temporal.

Para Feature Engineering, também podemos posteriormente extrair diretamente a hora.

In [14]:
# Pandas
df_pd["Time"] = pd.to_datetime(
    df_pd["Time"],
    format="%H:%M:%S",
    errors="coerce"
)

df_pd["Time"].head()

0   1900-01-01 12:29:38
1   1900-01-01 18:01:39
2   1900-01-01 08:56:10
3   1900-01-01 17:17:25
4   1900-01-01 22:08:00
Name: Time, dtype: datetime64[ns]

In [ ]:
# Polars
df_pl = df_pl.with_columns(
    pl.col("Time").str.to_time(format="%H:%M:%S", strict=False) )

df_pl.select("Time").head()

shape: (5, 1)
┌──────────┐
│ Time     │
│ ---      │
│ time     │
╞══════════╡
│ 12:29:38 │
│ 18:01:39 │
│ 08:56:10 │
│ 17:17:25 │
│ 22:08:00 │
└──────────┘

## 🚨 10. Investigando valores ausentes

Não devemos preencher valores ausentes automaticamente.

Primeiro precisamos descobrir **onde** eles estão e depois investigar **por que** estão ausentes.

In [16]:
# Pandas — quantidade de valores ausentes
missing_pd = df_pd.isna().sum().sort_values(ascending=False)
missing_pd

Incomplete Rides Reason              141000
Incomplete Rides                     141000
Reason for cancelling by Customer    139500
Cancelled Rides by Customer          139500
Cancelled Rides by Driver            123000
Driver Cancellation Reason           123000
Driver Ratings                        57000
Customer Rating                       57000
Avg CTAT                              48000
Ride Distance                         48000
Booking Value                         48000
Payment Method                        48000
Avg VTAT                              10500
Customer ID                               0
Booking Status                            0
Booking ID                                0
Time                                      0
Date                                      0
Pickup Location                           0
Drop Location                             0
Vehicle Type                              0
dtype: int64

In [17]:
# Pandas — percentual
missing_percent_pd = (
    df_pd.isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

missing_percent_pd

Incomplete Rides Reason              94.0
Incomplete Rides                     94.0
Reason for cancelling by Customer    93.0
Cancelled Rides by Customer          93.0
Cancelled Rides by Driver            82.0
Driver Cancellation Reason           82.0
Driver Ratings                       38.0
Customer Rating                      38.0
Avg CTAT                             32.0
Ride Distance                        32.0
Booking Value                        32.0
Payment Method                       32.0
Avg VTAT                              7.0
Customer ID                           0.0
Booking Status                        0.0
Booking ID                            0.0
Time                                  0.0
Date                                  0.0
Pickup Location                       0.0
Drop Location                         0.0
Vehicle Type                          0.0
dtype: float64

In [18]:
# Polars — quantidade de valores nulos
df_pl.null_count()

shape: (1, 21)
┌──────┬──────┬────────────┬─────────┬───┬──────────┬─────────┬──────────────────┬─────────────────┐
│ Date ┆ Time ┆ Booking ID ┆ Booking ┆ … ┆ Ride     ┆ Driver  ┆ Customer Rating  ┆ Payment Method  │
│ ---  ┆ ---  ┆ ---        ┆ Status  ┆   ┆ Distance ┆ Ratings ┆ ---              ┆ ---             │
│ u32  ┆ u32  ┆ u32        ┆ ---     ┆   ┆ ---      ┆ ---     ┆ u32              ┆ u32             │
│      ┆      ┆            ┆ u32     ┆   ┆ u32      ┆ u32     ┆                  ┆                 │
╞══════╪══════╪════════════╪═════════╪═══╪══════════╪═════════╪══════════════════╪═════════════════╡
│ 0    ┆ 0    ┆ 0          ┆ 0       ┆ … ┆ 0        ┆ 0       ┆ 0                ┆ 0               │
└──────┴──────┴────────────┴─────────┴───┴──────────┴─────────┴──────────────────┴─────────────────┘

## 🧠 11. Ausência estrutural × ausência inesperada

Considere uma corrida com:

```text
Booking Status = No Driver Found
```

É possível que informações relacionadas ao motorista, como `Driver Ratings`, não existam.

Isso pode ser uma **ausência estrutural**, e não necessariamente um erro.

Agora considere:

```text
Booking Status = Completed
Booking Value = NaN
```

Essa situação merece investigação.

> **Pergunta:** devemos simplesmente substituir todos os `NaN` por zero?

## 📊 12. Analisando os status das corridas

In [19]:
# Pandas
df_pd["Booking Status"].value_counts()

Booking Status
Completed                93000
Cancelled by Driver      27000
No Driver Found          10500
Cancelled by Customer    10500
Incomplete                9000
Name: count, dtype: int64

In [20]:
# Polars
df_pl["Booking Status"].value_counts()

shape: (5, 2)
┌───────────────────────┬───────┐
│ Booking Status        ┆ count │
│ ---                   ┆ ---   │
│ str                   ┆ u32   │
╞═══════════════════════╪═══════╡
│ Cancelled by Customer ┆ 10500 │
│ No Driver Found       ┆ 10500 │
│ Cancelled by Driver   ┆ 27000 │
│ Completed             ┆ 93000 │
│ Incomplete            ┆ 9000  │
└───────────────────────┴───────┘

## 🔍 13. Valores ausentes por status

In [21]:
# Pandas
df_pd.groupby("Booking Status")["Booking Value"].apply(
    lambda x: x.isna().sum()
)

Booking Status
Cancelled by Customer    10500
Cancelled by Driver      27000
Completed                    0
Incomplete                   0
No Driver Found          10500
Name: Booking Value, dtype: int64

In [22]:
# Polars
df_pl.group_by("Booking Status").agg(
    pl.col("Booking Value").null_count().alias("Booking_Value_Nulos")
)

shape: (5, 2)
┌───────────────────────┬─────────────────────┐
│ Booking Status        ┆ Booking_Value_Nulos │
│ ---                   ┆ ---                 │
│ str                   ┆ u32                 │
╞═══════════════════════╪═════════════════════╡
│ Incomplete            ┆ 0                   │
│ No Driver Found       ┆ 0                   │
│ Cancelled by Customer ┆ 0                   │
│ Cancelled by Driver   ┆ 0                   │
│ Completed             ┆ 0                   │
└───────────────────────┴─────────────────────┘

## 🚨 14. Corridas concluídas sem `Booking Value`

In [23]:
# Pandas
completed_pd = df_pd[
    df_pd["Booking Status"] == "Completed"
]

completed_pd[
    completed_pd["Booking Value"].isna()
]

Empty DataFrame
Columns: [Date, Time, Booking ID, Booking Status, Customer ID, Vehicle Type, Pickup Location, Drop Location, Avg VTAT, Avg CTAT, Cancelled Rides by Customer, Reason for cancelling by Customer, Cancelled Rides by Driver, Driver Cancellation Reason, Incomplete Rides, Incomplete Rides Reason, Booking Value, Ride Distance, Driver Ratings, Customer Rating, Payment Method]
Index: []

In [24]:
# Polars
completed_pl = df_pl.filter(
    pl.col("Booking Status") == "Completed"
)

completed_pl.filter(
    pl.col("Booking Value").is_null()
)

shape: (0, 21)
┌──────┬──────┬────────────┬─────────┬───┬──────────┬─────────┬──────────────────┬─────────────────┐
│ Date ┆ Time ┆ Booking ID ┆ Booking ┆ … ┆ Ride     ┆ Driver  ┆ Customer Rating  ┆ Payment Method  │
│ ---  ┆ ---  ┆ ---        ┆ Status  ┆   ┆ Distance ┆ Ratings ┆ ---              ┆ ---             │
│ date ┆ time ┆ str        ┆ ---     ┆   ┆ ---      ┆ ---     ┆ str              ┆ str             │
│      ┆      ┆            ┆ str     ┆   ┆ str      ┆ str     ┆                  ┆                 │
╞══════╪══════╪════════════╪═════════╪═══╪══════════╪═════════╪══════════════════╪═════════════════╡
└──────┴──────┴────────────┴─────────┴───┴──────────┴─────────┴──────────────────┴─────────────────┘

### 💬 Debate

Se uma corrida foi `Completed`, mas não possui `Booking Value`, o que devemos fazer?

Possibilidades:

1. excluir o registro;
2. substituir por zero;
3. estimar o valor;
4. procurar a informação em outra fonte;
5. manter como ausente;
6. investigar a origem do problema.

A decisão depende do contexto do negócio.

## 🔁 15. Verificando duplicidades

In [25]:
# Pandas
duplicados_pd = df_pd.duplicated().sum()
print("Linhas duplicadas:", duplicados_pd)

Linhas duplicadas: 0

In [26]:
# Polars
duplicados_pl = df_pl.is_duplicated().sum()
print("Linhas duplicadas:", duplicados_pl)

Linhas duplicadas: 0

## 🔑 16. Investigando `Booking ID` como identificador

In [27]:
# Pandas
print("Registros:", len(df_pd))
print("Booking IDs únicos:", df_pd["Booking ID"].nunique())

Registros: 150000
Booking IDs únicos: 148767

In [28]:
# Polars
print("Registros:", df_pl.height)
print("Booking IDs únicos:", df_pl["Booking ID"].n_unique())

Registros: 150000
Booking IDs únicos: 148767

## 📋 17. Variáveis categóricas

In [ ]:
# Pandas
print("Booking Status:")
display(df_pd["Booking Status"].value_counts()) #display para exibir o resultado de forma mais agradável no Jupyter Notebook

print("Vehicle Type:")
display(df_pd["Vehicle Type"].value_counts())

print("Payment Method:")
display(df_pd["Payment Method"].value_counts())

Booking Status:

Booking Status
Completed                93000
Cancelled by Driver      27000
No Driver Found          10500
Cancelled by Customer    10500
Incomplete                9000
Name: count, dtype: int64

Vehicle Type:

Vehicle Type
Auto             37419
Go Mini          29806
Go Sedan         27141
Bike             22517
Premier Sedan    18111
eBike            10557
Uber XL           4449
Name: count, dtype: int64

Payment Method:

Payment Method
UPI            45909
Cash           25367
Uber Wallet    12276
Credit Card    10209
Debit Card      8239
Name: count, dtype: int64

In [30]:
# Polars
print("Booking Status")
display(df_pl["Booking Status"].value_counts())

print("Vehicle Type")
display(df_pl["Vehicle Type"].value_counts())

print("Payment Method")
display(df_pl["Payment Method"].value_counts())

Booking Status

shape: (5, 2)
┌───────────────────────┬───────┐
│ Booking Status        ┆ count │
│ ---                   ┆ ---   │
│ str                   ┆ u32   │
╞═══════════════════════╪═══════╡
│ Completed             ┆ 93000 │
│ Incomplete            ┆ 9000  │
│ Cancelled by Driver   ┆ 27000 │
│ No Driver Found       ┆ 10500 │
│ Cancelled by Customer ┆ 10500 │
└───────────────────────┴───────┘

Vehicle Type

shape: (7, 2)
┌───────────────┬───────┐
│ Vehicle Type  ┆ count │
│ ---           ┆ ---   │
│ str           ┆ u32   │
╞═══════════════╪═══════╡
│ eBike         ┆ 10557 │
│ Premier Sedan ┆ 18111 │
│ Go Sedan      ┆ 27141 │
│ Auto          ┆ 37419 │
│ Uber XL       ┆ 4449  │
│ Bike          ┆ 22517 │
│ Go Mini       ┆ 29806 │
└───────────────┴───────┘

Payment Method

shape: (6, 2)
┌────────────────┬───────┐
│ Payment Method ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Cash           ┆ 25367 │
│ Debit Card     ┆ 8239  │
│ Credit Card    ┆ 10209 │
│ Uber Wallet    ┆ 12276 │
│ UPI            ┆ 45909 │
│ null           ┆ 48000 │
└────────────────┴───────┘

# 🧩 18. Feature Engineering

Depois de entender os dados, podemos criar novas variáveis.

Vamos criar:

- `Ano`
- `Mes`
- `Dia`
- `Dia_Semana`
- `Hora`
- `Categoria_Distancia`

In [ ]:
# Pandas — calendário
df_pd["Ano"] = df_pd["Date"].dt.year #dt. extractor de data e hora do pandas, permite acessar atributos como ano, mês, dia, hora, minuto, segundo, etc.
df_pd["Mes"] = df_pd["Date"].dt.month
df_pd["Dia"] = df_pd["Date"].dt.day
df_pd["Dia_Semana"] = df_pd["Date"].dt.dayofweek

# Pandas — hora
df_pd["Hora"] = df_pd["Time"].dt.hour

df_pd[[
    "Date", "Time", "Ano", "Mes", "Dia", "Dia_Semana", "Hora"
]].head()

        Date                Time   Ano  Mes  Dia  Dia_Semana  Hora
0 2024-03-23 1900-01-01 12:29:38  2024    3   23           5    12
1 2024-11-29 1900-01-01 18:01:39  2024   11   29           4    18
2 2024-08-23 1900-01-01 08:56:10  2024    8   23           4     8
3 2024-10-21 1900-01-01 17:17:25  2024   10   21           0    17
4 2024-09-16 1900-01-01 22:08:00  2024    9   16           0    22

In [32]:
# Polars — calendário e hora
df_pl = df_pl.with_columns(
    pl.col("Date").dt.year().alias("Ano"),
    pl.col("Date").dt.month().alias("Mes"),
    pl.col("Date").dt.day().alias("Dia"),
    pl.col("Date").dt.weekday().alias("Dia_Semana"),
    pl.col("Time").dt.hour().alias("Hora")
)

df_pl.select([
    "Date", "Time", "Ano", "Mes", "Dia", "Dia_Semana", "Hora"
]).head()

shape: (5, 7)
┌────────────┬──────────┬──────┬─────┬─────┬────────────┬──────┐
│ Date       ┆ Time     ┆ Ano  ┆ Mes ┆ Dia ┆ Dia_Semana ┆ Hora │
│ ---        ┆ ---      ┆ ---  ┆ --- ┆ --- ┆ ---        ┆ ---  │
│ date       ┆ time     ┆ i32  ┆ i8  ┆ i8  ┆ i8         ┆ i8   │
╞════════════╪══════════╪══════╪═════╪═════╪════════════╪══════╡
│ 2024-03-23 ┆ 12:29:38 ┆ 2024 ┆ 3   ┆ 23  ┆ 6          ┆ 12   │
│ 2024-11-29 ┆ 18:01:39 ┆ 2024 ┆ 11  ┆ 29  ┆ 5          ┆ 18   │
│ 2024-08-23 ┆ 08:56:10 ┆ 2024 ┆ 8   ┆ 23  ┆ 5          ┆ 8    │
│ 2024-10-21 ┆ 17:17:25 ┆ 2024 ┆ 10  ┆ 21  ┆ 1          ┆ 17   │
│ 2024-09-16 ┆ 22:08:00 ┆ 2024 ┆ 9   ┆ 16  ┆ 1          ┆ 22   │
└────────────┴──────────┴──────┴─────┴─────┴────────────┴──────┘

## 📏 19. Criando categorias de distância

In [34]:
# Pandas
df_pd["Categoria_Distancia"] = pd.cut(
    df_pd["Ride Distance"],
    bins=[-float("inf"), 5, 15, float("inf")],
    labels=["Curta", "Média", "Longa"]
)

df_pd[["Ride Distance", "Categoria_Distancia"]].head()

   Ride Distance Categoria_Distancia
0            NaN                 NaN
1           5.73               Média
2          13.58               Média
3          34.02               Longa
4          48.21               Longa

In [37]:
# Polars
df_pl = df_pl.with_columns(
    # strict=False converte textos invalidos como "null" para o tipo null nativo do Polars
    pl.col("Ride Distance").cast(pl.Float64, strict=False).alias("Ride Distance")
).with_columns(
    pl.when(pl.col("Ride Distance") <= 5)
      .then(pl.lit("Curta"))
      .when(pl.col("Ride Distance") <= 15)
      .then(pl.lit("Média"))
      .when(pl.col("Ride Distance") > 15)
      .then(pl.lit("Longa"))
      .otherwise(pl.lit("Sem Informação")) # Trata os valores que eram nulos/invalidos
      .alias("Categoria_Distancia")
)

df_pl.select([
    "Ride Distance", "Categoria_Distancia"
]).head(10)

shape: (10, 2)
┌───────────────┬─────────────────────┐
│ Ride Distance ┆ Categoria_Distancia │
│ ---           ┆ ---                 │
│ f64           ┆ str                 │
╞═══════════════╪═════════════════════╡
│ null          ┆ Sem Informação      │
│ 5.73          ┆ Média               │
│ 13.58         ┆ Média               │
│ 34.02         ┆ Longa               │
│ 48.21         ┆ Longa               │
│ 4.85          ┆ Curta               │
│ 41.24         ┆ Longa               │
│ 6.56          ┆ Média               │
│ null          ┆ Sem Informação      │
│ 10.36         ┆ Média               │
└───────────────┴─────────────────────┘

## 💰 20. Estatísticas de `Booking Value`

In [38]:
# Pandas
df_pd["Booking Value"].describe()

count    102000.000000
mean        508.295912
std         395.805774
min          50.000000
25%         234.000000
50%         414.000000
75%         689.000000
max        4277.000000
Name: Booking Value, dtype: float64

In [41]:
# Polars
df_pl.select("Booking Value").describe()

shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ Booking Value │
│ ---        ┆ ---           │
│ str        ┆ str           │
╞════════════╪═══════════════╡
│ count      ┆ 150000        │
│ null_count ┆ 0             │
│ mean       ┆ null          │
│ std        ┆ null          │
│ min        ┆ 100           │
│ 25%        ┆ null          │
│ 50%        ┆ null          │
│ 75%        ┆ null          │
│ max        ┆ null          │
└────────────┴───────────────┘

In [ ]:
####### POnto de atenção

#Pandas: É mais permissivo e faz inferências de tipo ocultas, o que facilita no início, mas pode mascarar problemas.

#Polars: É extremamente rigoroso com tipos de dados. Se houver uma única palavra como "null" em uma coluna numérica, ele assumirá que a coluna inteira é de texto para evitar corrupção silenciosa de dados.

## 🚗 21. Distância × valor

In [ ]:
# Pandas
df_pd[
    ["Ride Distance", "Booking Value"]
].corr() # corr() calcula a correlação entre as colunas numéricas do DataFrame, retornando uma matriz de correlação que mostra a relação entre cada par de variáveis. 
                        # O valor da correlação varia de -1 a 1, onde valores próximos a 1 indicam uma forte correlação positiva, 
                        #valores próximos a -1 indicam uma forte correlação negativa e valores próximos a 0 indicam pouca ou nenhuma correlação.

               Ride Distance  Booking Value
Ride Distance       1.000000       0.005174
Booking Value       0.005174       1.000000

In [43]:
# Polars
df_pl.select(
    pl.corr("Ride Distance", "Booking Value")
)

shape: (1, 1)
┌───────────────┐
│ Ride Distance │
│ ---           │
│ f64           │
╞═══════════════╡
│ 0.005174      │
└───────────────┘

## 📊 22. Agregações — valor médio por tipo de veículo

In [44]:
# Pandas
df_pd.groupby("Vehicle Type")["Booking Value"].mean().sort_values(
    ascending=False
)

Vehicle Type
Go Sedan         511.503385
Bike             510.200299
Premier Sedan    509.568169
Go Mini          507.684934
Auto             506.725241
eBike            503.897090
Uber XL          501.816749
Name: Booking Value, dtype: float64

In [45]:
# Polars
df_pl.group_by("Vehicle Type").agg(
    pl.col("Booking Value").mean().alias("Valor_Medio")
).sort(
    "Valor_Medio",
    descending=True
)

shape: (7, 2)
┌───────────────┬─────────────┐
│ Vehicle Type  ┆ Valor_Medio │
│ ---           ┆ ---         │
│ str           ┆ str         │
╞═══════════════╪═════════════╡
│ Premier Sedan ┆ null        │
│ Go Mini       ┆ null        │
│ eBike         ┆ null        │
│ Go Sedan      ┆ null        │
│ Bike          ┆ null        │
│ Uber XL       ┆ null        │
│ Auto          ┆ null        │
└───────────────┴─────────────┘

# 🧠 23. Comparação Pandas × Polars

| Operação | Pandas | Polars |
|---|---|---|
| Ler CSV | `pd.read_csv()` | `pl.read_csv()` |
| Primeiras linhas | `.head()` | `.head()` |
| Dimensões | `.shape` | `.shape` |
| Colunas | `.columns` | `.columns` |
| Tipos | `.dtypes` | `.schema` |
| Nulos | `.isna()` | `.null_count()` |
| Filtrar | `df[condição]` | `.filter()` |
| Agrupar | `.groupby()` | `.group_by()` |
| Ordenar | `.sort_values()` | `.sort()` |
| Criar coluna | `df["nova"] = ...` | `.with_columns()` |
| Estatísticas | `.describe()` | `.describe()` |
| Correlação | `.corr()` | `pl.corr()` |

> O objetivo não é escolher uma biblioteca "vencedora", mas compreender diferentes formas de trabalhar com dados tabulares.

# 🧠 24. Conclusão

Preparar dados não é simplesmente executar comandos de limpeza.

É um processo de:

```text
DATASET
   ↓
INSPECIONAR
   ↓
QUESTIONAR
   ↓
ENTENDER
   ↓
DECIDIR
   ↓
TRATAR
   ↓
VALIDAR
   ↓
DATASET PREPARADO
```

### Regra de ouro

> ## **Antes de corrigir um dado, procure entender por que ele está daquela maneira.**

Um bom Data Scientist não apenas sabe escrever:

```python
df.dropna()
```

Ele sabe responder:

> **"Por que devo remover esse dado?"**